resources:
  - name: myAppRepo
    type: GitRepo
    configuration:
      gitProvider: github_admin
      path: kfiravr2/pipelines-examples

pipelines:
  - name: pipeline_hello_world
    configuration:
      environmentVariables:
        readOnly:
          MY_MESSAGE: '"Hello World!"'
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: slack
        execution:
          onComplete:
            - send_notification slack --text "Hello"
          onFailure:
            - send_notification slack --text "The build failed"
         # onExecute:
          #  - send_notification slack --text "Hello". ##- echo $MY_MESSAGE
           # - echo “running CI for master”
