resources:
  - name: myAppRepo
    type: GitRepo
    configuration:
      gitProvider: github_admin
      path: kfiravr2/pipelines-examples
      
  - name: cron_trigger
    type: CronTrigger
    configuration:
      interval: '*/5 * * * *'     # Every 5 minutes

pipelines:
  - name: pipeline_hello_world
    configuration:
      environmentVariables:
        readOnly:
          MY_MESSAGE: '"Hello World!"'
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: myAppRepo
        execution:
          onExecute:
            - echo $MY_MESSAGE
            - echo "running CI for master"
            
    - name: pipeline_scheduled_triggers
    - steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: cron_trigger
        execution:
          onExecute:
            - printenv
