resources:
  - name: myAppRepo
    type: GitRepo
    configuration:
      gitProvider: GitHub_kfiravr2
      path: kfiravr2/pipelines-examples/hello-world

pipelines:
  - name: pipeline_hello_world
    configuration:
      environmentVariables:
        readOnly:
          MY_MESSAGE: '"Hello World!"'
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: myAppRepo
        execution:
          onExecute:
            - echo $MY_MESSAGE
            - echo “running CI for master”
